### PR TITLE
allow custom return url

### PR DESCRIPTION
**Pull request by bombnp**
allow custom return url after google auth to allow persisting url after login

for security reasons, cross-origin return urls are only allowed in dev environment (for local frontend). Beta and prod return urls must begin with backendPublicUrl

cc @paphonb

### CODE REVIEW

**Review by saenyakorn — APPROVED** [review]
เยี่ยม กำลังจะขอเลย

**Comment by bombnp** [comment]
waiting for @paphonb

**Comment by saengowp** [comment]
Let me think for a sec.

**Comment by saengowp** [comment]
Yup. I think its all good. I notice a CSRF attack but that's my fault.

**Review by saengowp — APPROVED** [review]

**Comment by bombnp** [comment]
> Yup. I think its all good. I notice a CSRF attack but that's my fault.

fix next PR?

**Review by paphonb — APPROVED** [review]

**Pull request merged**
